Try to make sure prowler cleans up its temporary files

diff --git a/prowler b/prowler
--- a/prowler
+++ b/prowler
@@ -162,6 +162,9 @@ while getopts ":hlLkqp:r:c:g:f:m:M:E:enbVsx:" OPTION; do
    esac
 done
 
+# Clean up any temp files when prowler quits unexpectedly
+trap "{ rm -f /tmp/prowler*.policy.*; }" EXIT
+
 . $PROWLER_DIR/include/colors
 . $PROWLER_DIR/include/os_detector
 . $PROWLER_DIR/include/aws_profile_loader
@@ -194,12 +197,12 @@ for checks in $(ls $PROWLER_DIR/checks/check*|grep -v check_sample); do
 	. "$checks"
 done
 
-# include checks if external folder is specified 
-if [[ $EXTERNAL_CHECKS_PATH ]]; then 
+# include checks if external folder is specified
+if [[ $EXTERNAL_CHECKS_PATH ]]; then
   for checks in $(ls $EXTERNAL_CHECKS_PATH/check*); do
 	. "$checks"
   done
-fi 
+fi
 
 # Function to show the title of the check
 # using this way instead of arrays to keep bash3 (osx) and bash4(linux) compatibility
@@ -292,7 +295,7 @@ execute_group_by_id() {
 	done
 }
 
-# Function to execute all checks in all groups except extras if -e is invoked 
+# Function to execute all checks in all groups except extras if -e is invoked
 execute_all() {
 	for i in "${!GROUP_TITLE[@]}"; do
     if [[ $EXTRAS ]]; then
@@ -309,7 +312,7 @@ show_all_titles() {
   MAIN_GROUPS=(1 2 3 4 7)
   for i in "${MAIN_GROUPS[@]}"; do
 		show_group_title $i
-		# Display the title of the checks in groups 1,2,3,4 and 7 
+		# Display the title of the checks in groups 1,2,3,4 and 7
     # Any other group has checks in these groups
 		IFS=',' read -ra CHECKS <<< ${GROUP_CHECKS[$i]}
 		for j in ${CHECKS[@]}; do
