refactor(outputs): Consolidate Prowler output functions (#1180)
* chore(db providers): db providers first version

* chore(db provider): added db provider setup into Readme

* fix(csv_line): csv_line out of conditional

* fix(README): text instead of varchar in table

* fix(help): help message extended

Co-authored-by: Sergio Garcia <38561120+sergargar@users.noreply.github.com>

* fix(typo): Update README.md

Co-authored-by: Pepe Fagoaga <pepe@verica.io>

* fix(table): add if not exists

Co-authored-by: Pepe Fagoaga <pepe@verica.io>

* fix(typo): Readme postgreSQL

Co-authored-by: Pepe Fagoaga <pepe@verica.io>

* fix(db_connector): details to add a new provider

* fix(typo): Uppercase Prowler

Co-authored-by: Toni de la Fuente <toni@blyx.com>

* fix(prowler): deleted unused variable

* chore(checks): test db connector previous to send data

* chore(input tests): input tests moved to main

* fix(typo): Readme typos

* chore(table): table name from pgpass file

* fix(grep test): Added missing -E flag

* chore(table): check of table name and Readme

* chore(error colors): Added error colors

* chore(inputcheck): checks about mode and output inputs into main

* fix(inputs) custom output file name

* fix(outputs): comment profile

* chore(textXXX): both 3 textfunctions using general

* fix(allowlist): allowlist check included as function

* fix(headers): Add headers to certain output files

* fix(reformulate): change structure and delete comments

* fix(testing): Input test after load includes

* fix(variables): Added named vars

* fix(colors): Deleted unused colors

* fix(outputs): fine tuning

* fix(outputs): allowlist parameters read

* fix(allowlist): allowlist logic reformulated

* fix(REPREGION): REPREGION change by REGION_FROM_CHECK

Co-authored-by: Sergio Garcia <38561120+sergargar@users.noreply.github.com>
Co-authored-by: Pepe Fagoaga <pepe@verica.io>
Co-authored-by: Toni de la Fuente <toni@blyx.com>

diff --git a/prowler b/prowler
--- a/prowler
+++ b/prowler
@@ -41,6 +41,7 @@ EXITCODE=0
 SEND_TO_SECURITY_HUB=0
 FAILED_CHECK_FAILED_SCAN=1
 PROWLER_START_TIME=$( date -u +"%Y-%m-%dT%H:%M:%S%z" )
+OUTPUT_DATE=$(date -u +"%Y%m%d%H%M%S")
 TITLE_ID=""
 TITLE_TEXT="CALLER ERROR - UNSET TITLE"
 ALLOWLIST_FILE=""
@@ -309,8 +310,7 @@ unset AWS_DEFAULT_OUTPUT
 . $PROWLER_DIR/include/db_connector
 
 
-
-
+#Parsing input options
 # Parses the check file into CHECK_ID's.
 if [[ -n "$CHECK_FILE" ]]; then
   if [[ -f $CHECK_FILE ]]; then
@@ -369,10 +369,65 @@ then
     fi
 fi
 
+# Check modes
+if [ -n "${MODE}" ]
+then
+  IFS=',' read -ra MODES <<< "${MODE}"
+  for MODE in "${MODES[@]}"; do
+    if [[ "$MODE" != "mono" && "$MODE" != "text" && "$MODE" != "csv" && "$MODE" != "json" && "$MODE" != "json-asff" && "$MODE" != "junit-xml" && "$MODE" != "html" ]]; then
+      echo -e "${OPTRED}ERROR!$OPTNORMAL Invalid output mode.  Choose text, mono, csv, json, json-asff, junit-xml or html. ./prowler -h for help"
+      EXITCODE=1
+      exit $EXITCODE
+    fi
+  done
+fi
+
+#Check output dir custom
+if [ -n "${OUTPUT_DIR_CUSTOM}" ]
+then
+    # If dir custom, mode has to be enabled (if you provide a custom directory it's because you want to store something)
+    if [  "${MODE}" != 'text' ]
+    then
+        # Check if custom folder exists
+        if [ ! -d "${OUTPUT_DIR_CUSTOM}" ]
+        then
+            echo "$OPTRED ERROR!$OPTNORMAL directory \"$OUTPUT_DIR_CUSTOM\" does not exist."
+            exit 1
+        else
+            OUTPUT_DIR=$OUTPUT_DIR_CUSTOM
+        fi
+    else 
+        echo "$OPTRED ERROR!$OPTNORMAL - When using custom directory output Mode (-M) has to be set as well. Use -h for help."
+        exit 1
+    fi   
+ # If custom output dir is not provided output dir -> default
+ else 
+        OUTPUT_DIR="${PROWLER_DIR}/output"
+        if [ ! -d "${OUTPUT_DIR}" ]
+        then
+            mkdir -p "${OUTPUT_DIR}"
+        fi
+ fi
+
+ # End of input parameters tests 
+ 
 # Pre-process allowlist file if supplied
 if [[ -n "$ALLOWLIST_FILE" ]]; then
   allowlist
 fi
+
+# Create output file name
+if [ -n "${OUTPUT_FILE_NAME}" ]
+then
+  OUTPUT_FILE_NAME="${OUTPUT_DIR}/$OUTPUT_FILE_NAME"
+else
+  OUTPUT_FILE_NAME="${OUTPUT_DIR}/prowler-output-${ACCOUNT_NUM}-${OUTPUT_DATE}"
+fi
+
+# Add headers to certain output files
+output_files_init
+
+
 
 # Load all of the groups of checks inside groups folder named as "groupNumber*"
 for group in $(ls $PROWLER_DIR/groups/group[0-9]*|grep -v groupN_sample); do
