[break]refactor(main): execute checks functions

diff --git a/prowler b/prowler
--- a/prowler
+++ b/prowler
@@ -140,17 +140,12 @@ ALLOWLIST_FILE=""
 TOTAL_CHECKS=()
 
 # This function comes from include/awscli_detector
-# REVIEW
 set_aws_default_output
 
 ############################################################################################
-# REVIEW
 # Function to show the title of a group, by numeric id
 show_group_title() {
-	# when csv mode is used, no group title is shown
-  # if [[ "$MODE" != "csv" ]]; then
-      textTitle "${GROUP_NUMBER[$1]}" "${GROUP_TITLE[$1]}"
-  # fi
+  textTitle "${GROUP_NUMBER[$1]}" "${GROUP_TITLE[$1]}"
 }
 
 # REVIEW
@@ -183,14 +178,46 @@ get_checks() {
 # If '-g <group_id>' has been specified, only show the titles of checks within the specified group
   # reading groups from GROUP_ID_READ
   # Now we can read groups comma or space splitted
-if [[ "${GROUP_ID_READ}" ]] 
+
+#Parsing input options
+# Parses the check file into CHECK_ID's.
+if [[ -n "$CHECK_FILE" ]]
 then
-    # Iterate over every group removing echar comma
-    for GROUP_IDENTIFIER in ${GROUP_ID_READ//,/ }
+  if [[ -f $CHECK_FILE ]]
+  then
+    # Parses the file, converting it to a comma seperated list. Ignores all # comments and removes extra blank spaces
+    # REVIEW THIS OPTION -C
+    TOTAL_CHECKS="$(awk '!/^[[:space:]]*#/{print }' <(cat ${CHECK_FILE} | sed 's/[[:space:]]*#.*$//g;/^$/d' | sed 'H;1h;$!d;x;y/\n/,/' | tr -d ' '))"
+  else
+    # If the file doesn't exist, exits Prowler
+    echo "$CHECK_FILE does not exist"
+    EXITCODE=1
+    exit $EXITCODE
+  fi
+elif [[ "${GROUP_ID_READ}" ]]
+then
+  for GROUP in "${GROUP_ID[@]}"
+  do
+    if [[ "${GROUP}" == "${GROUP_ID_READ}" ]]
+    then
+      IS_GROUP=1
+    fi
+  done
+  if [[ IS_GROUP -eq 0 ]]
+  then
+      textFail "Group ${GROUP_ID_READ} does not exist. Valid check groups are: ${GROUP_ID[*]}"
+      exit $EXITCODE
+  fi
+  # Iterate over every group removing echar comma
+  for GROUP_IDENTIFIER in ${GROUP_ID_READ//,/ }
+  do
+    # Iterate over every GroupID to find the belongin checks
+    for I in "${!GROUP_ID[@]}"
     do
-      # Iterate over every GroupID to find the belongin checks
-      for I in "${!GROUP_ID[@]}"
-      do
+      if [[ "${EXTRAS}" -eq 1 && "${GROUP_ID[I]}" == "extras" ]]
+      then
+        continue
+      else
         if [[ "${GROUP_ID[I]}" == "${GROUP_IDENTIFIER}" ]]
         then
           # shellcheck disable=SC2068
@@ -203,26 +230,34 @@ then
             fi
           done
         fi
-      done
-
+      fi
     done
-    TOTAL_CHECKS=("${CHECK_LIST_BY_GROUP[@]}")
+  done
+  TOTAL_CHECKS=("${CHECK_LIST_BY_GROUP[@]}")
 elif [ -n "${CHECK_ID}" ]
-then 
+then
     IFS=',' read -ra TOTAL_CHECKS <<< "${CHECK_ID}"
-else 
+else
+  # if -e is passed we dont want extra checks
+  if [[ "${EXTRAS}" -eq 1 ]]
+    then
+      EXCLUDE_CHECK_ID=("${EXCLUDE_CHECK_ID[@]}" "${GROUP_CHECKS[7]}")
+  fi
   for CHECK in $(ls $PROWLER_DIR/checks/check*|grep -v check_sample); do
 	  # Relative path required to load every check
     CHECK_DIR_NAME=$(basename "${CHECK}")
     # Name of the check
     CHECK_NAME=${CHECK_DIR_NAME//check_/}
     # If a group identifier is passed
+
     if ! grep -E -w -q "${EXCLUDE_CHECK_ID//,/|}" <<< "${CHECK_NAME}"
     then
       TOTAL_CHECKS+=("${CHECK_NAME}")
     fi
+
   done
 fi
+
 # Iterate over the final list of checks after being parsed all the input options to load the selected checks
 for LOAD_PATH_CHECK in ${TOTAL_CHECKS[*]}
 do
@@ -235,12 +270,6 @@ do
 done
 
 }
-
-# GROUP_ID[1]='group1'
-# GROUP_NUMBER[1]='1.0'
-# GROUP_TITLE[1]='Identity and Access Management - CIS only - [group1] ***********'
-# GROUP_RUN_BY_DEFAULT[1]='Y' # run it when execute_all is called
-# GROUP_CHECKS[1]='check11,check12,check13,check14,check15,check16,check17,check18,check19,check110,check111,check112,check113,check114,check115,check116,check117,check118,check119,check120,check121,check122'
 
 ############################################################################################
 
@@ -259,35 +288,6 @@ show_all_check_titles() {
   local CHECK_LIST_BY_GROUP
   local check_id
   local group_index
-
-  # # If '-g <group_id>' has been specified, only show the titles of checks within the specified group
-  # # reading groups from GROUP_ID_READ
-  # # Now we can read groups comma or space splitted
-  # if [[ "${GROUP_ID_READ}" ]]
-  # then
-  #   # Iterate over every group removing echar comma
-  #   for GROUP_IDENTIFIER in ${GROUP_ID_READ//,/ }
-  #   do
-  #     # Iterate over every GroupID to find the belongin checks
-  #     for I in "${!GROUP_ID[@]}"
-  #     do
-  #       if [[ "${GROUP_ID[I]}" == "${GROUP_IDENTIFIER}" ]]
-  #       then
-  #         # shellcheck disable=SC2068
-  #         for CHECK_IDENTIFIER in ${GROUP_CHECKS[I]//,/ }
-  #         do
-  #           # Include every check if not present
-  #           if [[ ! "${CHECK_LIST_BY_GROUP[*]}" =~ ${CHECK_IDENTIFIER} ]] && [[ "${TOTAL_CHECKS[*]}" =~ ${CHECK_IDENTIFIER} ]]
-  #           then
-  #             CHECK_LIST_BY_GROUP+=("${CHECK_IDENTIFIER}")
-  #           fi
-  #         done
-  #       fi
-  #     done
-
-  #   done
-  #   TOTAL_CHECKS=("${CHECK_LIST_BY_GROUP[@]}")
-  # fi
 
   for CHECK_ID in ${TOTAL_CHECKS[*]}
   do
@@ -458,7 +458,6 @@ get_checks
 
 if [[ ${LIST_CHECKS} -eq 1 ]]; then
   show_all_check_titles
-  #exit
 fi
 
 if [[ ${LIST_GROUPS} -eq 1 ]]; then
@@ -495,20 +494,6 @@ unset AWS_DEFAULT_OUTPUT
 # Check OS
 os_detector
 TIMESTAMP=$(get_iso8601_timestamp)
-
-#Parsing input options
-# Parses the check file into CHECK_ID's.
-if [[ -n "$CHECK_FILE" ]]; then
-  if [[ -f $CHECK_FILE ]]; then
-    # Parses the file, converting it to a comma seperated list. Ignores all # comments and removes extra blank spaces
-    CHECK_ID="$(awk '!/^[[:space:]]*#/{print }' <(cat $CHECK_FILE | sed 's/[[:space:]]*#.*$//g;/^$/d' | sed 'H;1h;$!d;x;y/\n/,/' | tr -d ' '))"
-  else
-    # If the file doesn't exist, exits Prowler
-    echo "$CHECK_FILE does not exist"
-    EXITCODE=1
-    exit $EXITCODE
-  fi
-fi
 
 # Check database providers
 if [[ ${DATABASE_PROVIDER} ]]
@@ -556,13 +541,16 @@ then
 fi
 
 # Check modes
+# POSSIBLE FUNCTION HERE
+# REVIEW
 if [ -n "${MODE}" ]
 then
-# REVIEW LOGIC HERE
+  AVAILABLE_OUTPUT_MODES="mono|text|csv|json|json-asff|junit-xml|html"
   IFS=',' read -ra MODES <<< "${MODE}"
   for MODE in "${MODES[@]}"; do
-    if [[ "$MODE" != "mono" && "$MODE" != "text" && "$MODE" != "csv" && "$MODE" != "json" && "$MODE" != "json-asff" && "$MODE" != "junit-xml" && "$MODE" != "html" ]]; then
-      echo -e "${OPTRED}ERROR!$OPTNORMAL Invalid output mode.  Choose text, mono, csv, json, json-asff, junit-xml or html. ./prowler -h for help"
+    if ! grep -w -q -E "${AVAILABLE_OUTPUT_MODES}" <<< "${MODE}"
+    then
+      echo -e "${OPTRED}ERROR!$OPTNORMAL Invalid output mode. Choose text, mono, csv, json, json-asff, junit-xml or html. ./prowler -h for help"
       EXITCODE=1
       exit $EXITCODE
     fi
@@ -628,41 +616,26 @@ fi
 # Add headers to certain output files
 output_files_init
 
-
-
-
 # include checks if external folder is specified
+# REVIEW
 if [[ $EXTERNAL_CHECKS_PATH ]]; then
   custom_checks
 fi
 
-
-# # REVIEW THIS WITH THE FUNCTIONS WE HAVE
-# # Get a list of total checks available by ID
-# for i in "${!GROUP_TITLE[@]}"; do
-#   IFS=',' read -ra CHECKS <<< "${GROUP_CHECKS[$i]}"
-#   for j in "${CHECKS[@]}"; do
-#     TOTAL_CHECKS+=("$CHECK_ID_$j")
-#   done
-# done
-# #echo $TOTAL_CHECKS
-# # Remove duplicates, sort checks numerically, and store the result as an array
-# # Note: the sort mechanism relies on the fact that the check ID prefixes 'check' and 'extra' are both 5 characters long.
-# #       6th character is the section number, 7th character onwards is the individual ID (e.g. check110 = check 1 10)
-# #TOTAL_CHECKS=($(echo "${TOTAL_CHECKS[*]}" | tr ' ' '\n' | awk '!seen[$0]++' | sort -k 1.6,1.6n -k 1.7n))
-
 # Function to get all regions
 get_regions() {
   # Get list of regions based on include/whoami
-  REGIONS=$($AWSCLI ec2 describe-regions --query 'Regions[].RegionName' --output text $PROFILE_OPT --region $REGION_FOR_STS --region-names ${FILTERREGION//[,]/ } 2>&1)
-  ret=$?
-  if [[ $ret -ne 0 ]]; then
+  if ! REGIONS=$($AWSCLI ec2 describe-regions \
+            --query 'Regions[].RegionName' \
+            --output text ${PROFILE_OPT} \
+            --region "${REGION_FOR_STS}" \
+            --region-names ${FILTERREGION//[,]/ } 2>&1)
+  then
     echo "$OPTRED Access Denied trying to describe regions! Review permissions as described here: https://github.com/prowler-cloud/prowler/#requirements-and-installation $OPTNORMAL"
     EXITCODE=1
     exit $EXITCODE
   fi
 }
-
 
 
 # Function to execute the check
@@ -781,85 +754,12 @@ execute_check() {
   fi
 }
 
-# Function to execute all checks in a group
-execute_group() {
-    show_group_title $1
-    # run the checks in the group
-    IFS=',' read -ra CHECKS <<< ${GROUP_CHECKS[$1]}
-
-    # Exclude any checks specified
-    if [[ -n ${2} ]]; then
-        EXCLUDED_CHECKS=()
-        NEW_CHECKS=()
-        IFS=',' read -ra EXCLUDED_CHECKS <<< "${2},"
-        for exc in ${EXCLUDED_CHECKS[@]} ; do
-            for i in ${!CHECKS[@]} ; do
-                [[ ${CHECKS[i]} = ${exc} ]] && unset CHECKS[i]
-            done
-        done
-        unset EXCLUDED_CHECKS
-    fi
-    for i in ${CHECKS[@]}; do
-        execute_check ${i}
-    done
-}
-
-# Function to execute group by name
-execute_group_by_id() {
-  	for i in "${!GROUP_ID[@]}"; do
-		if [ "${GROUP_ID[$i]}" == "$1" ]; then
-			execute_group ${i} $2
-		fi
-	done
-}
-
-# Function to execute all checks in all groups except extras if -e is invoked
-execute_all() {
-  for i in "${!GROUP_TITLE[@]}"; do
-    if [[ $EXTRAS ]]; then
-      GROUP_RUN_BY_DEFAULT[7]='N'
-    fi
-    if [ "${GROUP_RUN_BY_DEFAULT[$i]}" == "Y" ]; then
-      execute_group $i
-    fi
-  done
-}
-
-
-
-# # Function to execute all checks but exclude some of them
-# get_all_checks_without_exclusion() {
-#   CHECKS_EXCLUDED=()
-#   local CHECKS_TO_EXCLUDE=()
-#   # Get a list of checks to exclude
-#   IFS=',' read -ra E_CHECKS <<< "$1"
-#   for E_CHECK in "${E_CHECKS[@]}"; do
-#     CHECKS_TO_EXCLUDE+=($E_CHECK)
-#   done
-#   # Create a list that contains all checks but excluded ones
-#   for i in "${TOTAL_CHECKS[@]}"; do
-#     local COINCIDENCE=false
-#     for x in "${CHECKS_TO_EXCLUDE[@]}"; do
-#       if [[ "$i" == "$x" ]]; then
-#         COINCIDENCE=true
-#       fi
-#     done
-#     if [[ "$COINCIDENCE" = false ]]; then
-#       CHECKS_EXCLUDED+=($i)
-#     fi
-#   done
-# }
-
 # REVIEW MOVER
 prowlerBanner
 
-
-
-
-
-
 # Check that jq is installed for JSON outputs
-if [[ " ${MODES[@]} " =~ " json " || " ${MODES[@]} " =~ " json-asff " ]]; then
+if [[ "${MODES[*]}" =~ "json" || "${MODES[*]}" =~ "json-asff" ]]
+then
   jq_detector
 fi
 
@@ -868,11 +768,13 @@ aws_cli_detector
 # aws_profile_loader
 aws_profile_loader
 
-if [[ "$SEND_TO_SECURITY_HUB" -eq 1 ]]; then
+if [[ "$SEND_TO_SECURITY_HUB" -eq 1 ]]
+then
   checkSecurityHubCompatibility
 fi
 
-if is_junit_output_enabled; then
+if is_junit_output_enabled
+then
   prepare_junit_output
 fi
 
@@ -898,7 +800,8 @@ then
   restoreInitialAWSCredentials
 fi
 
-if [[ -n "${ACCOUNT_TO_ASSUME}" || -n "${ROLE_TO_ASSUME}" ]]; then
+if [[ -n "${ACCOUNT_TO_ASSUME}" || -n "${ROLE_TO_ASSUME}" ]]
+then
   backupInitialAWSCredentials
   assume_role
 fi
@@ -913,25 +816,23 @@ case "$REGION" in
   ;;
 esac
 
-if ! GETCALLER=$("${AWSCLI}" sts get-caller-identity ${PROFILE_OPT} --output json --region "${REGION_FOR_STS}")
+if ! GETCALLER=$("${AWSCLI}" sts get-caller-identity \
+                  ${PROFILE_OPT} \
+                --output text \
+                --region "${REGION_FOR_STS}" \
+                --query '[Arn,UserId,Account]')
 then
     echo -e "$RED ERROR Getting credentials to run Prowler - EXITING! $NORMAL"
     EXITCODE=2
     exit $EXITCODE
 fi
+read -r CALLER_ARN USER_ID ACCOUNT_NUM <<< "${GETCALLER}"
 
-if [[ $ACCOUNT_TO_ASSUME ]]; then
+if [[ $ACCOUNT_TO_ASSUME ]]
+then
   ACCOUNT_NUM=$ACCOUNT_TO_ASSUME
-else
-  ACCOUNT_NUM=$(echo $GETCALLER | jq -r '.Account' 2>&1)
 fi
-
-CALLER_ARN=$(echo $GETCALLER | jq -r '.Arn' 2>&1)
-USER_ID=$(echo $GETCALLER | jq -r '.UserId' 2>&1)
-AWS_PARTITION=$(echo $CALLER_ARN| cut -d: -f2)
-echo $CALLER_ARN
-echo $USER_ID
-echo $AWS_PARTITION
+AWS_PARTITION=$(cut -d: -f2 <<< "${CALLER_ARN}")
 
 # Gather account data / test aws cli connectivity
 getWhoami
@@ -939,83 +840,20 @@ getWhoami
 # List regions
 get_regions
 
-# Execute group of checks if called with -g
-if [[ $GROUP_ID_READ ]];then
-  if [[ " ${GROUP_ID[@]} " =~ " ${GROUP_ID_READ} " ]]; then
-
-    execute_group_by_id ${GROUP_ID_READ} ${EXCLUDE_CHECK_ID}
-
-    #### ESTO SE PUEDE QUITAR SI SE HACE GLOBALMENT AL FINAL
-    if [[ "${MODES[@]}" =~ "html" ]]; then
-      addHtmlFooter >> ${OUTPUT_FILE_NAME}.$EXTENSION_HTML
-    fi
-    #### ESTO SE PUEDE QUITAR SI SE HACE GLOBALMENT AL FINAL
-    cleanTemp
-    scoring
-    #### ESTO SE PUEDE QUITAR SI SE HACE GLOBALMENT AL FINAL
-    if [[ $OUTPUT_BUCKET_NOASSUME ]]; then
-      restoreInitialAWSCredentials
-    fi
-    #### ESTO SE PUEDE QUITAR SI SE HACE GLOBALMENT AL FINAL
-    if [[ $OUTPUT_BUCKET ]]; then
-      copyToS3
-    fi
-    exit $EXITCODE
-  else
-    textFail "Group ${GROUP_ID_READ} does not exist. Use a valid check group ID i.e.: group1, extras, forensics-ready, etc."
-    show_all_group_titles
-    exit $EXITCODE
-  fi
-fi
-
-# Get a list of total checks excluding a list provided by the user and overwrite CHECK_ID with the result
-# if the list provided by the user contains an invalid check, this will be discarded.
-# if the list provided by the user contains  just one argument and is invalid, then it will be discarded and all tests will be executed
-if [[ ${EXCLUDE_CHECK_ID} ]];then
-  get_all_checks_without_exclusion ${EXCLUDE_CHECK_ID}
-  function join { local IFS="$1"; shift; echo "$*"; }
-  CHECKS_EXCLUDED=$(join , "${CHECKS_EXCLUDED[@]}")
-  CHECK_ID=${CHECKS_EXCLUDED}
-fi
-
-# Execute single check if called with -c
-if [[ $CHECK_ID ]];then
-  IFS=',' read -ra CHECKS <<< "$CHECK_ID"
-  for CHECK in "${CHECKS[@]}"; do
-    execute_check $CHECK
-  done
-
-  #### ESTO SE PUEDE QUITAR SI SE HACE GLOBALMENT AL FINAL
-  if [[ "${MODES[@]}" =~ "html" ]]; then
-    addHtmlFooter >> ${OUTPUT_FILE_NAME}.$EXTENSION_HTML
-  fi
-  #### ESTO SE PUEDE QUITAR SI SE HACE GLOBALMENT AL FINAL
-  if [[ $OUTPUT_BUCKET_NOASSUME ]]; then
-    restoreInitialAWSCredentials
-  fi
-  #### ESTO SE PUEDE QUITAR SI SE HACE GLOBALMENT AL FINAL
-  if [[ $OUTPUT_BUCKET ]]; then
-    copyToS3
-  fi
-  #### ESTO SE PUEDE QUITAR SI SE HACE GLOBALMENT AL FINAL
-  scoring
-  cleanTemp
-  exit $EXITCODE
-fi
-
-execute_all
+for CHECK in "${TOTAL_CHECKS[@]}"
+do
+  execute_check $CHECK
+done
 
 if [[ "${MODES[@]}" =~ "html" ]]; then
   addHtmlFooter >> ${OUTPUT_FILE_NAME}.$EXTENSION_HTML
 fi
-
-scoring
-cleanTemp
 if [[ $OUTPUT_BUCKET_NOASSUME ]]; then
   restoreInitialAWSCredentials
 fi
 if [[ $OUTPUT_BUCKET ]]; then
   copyToS3
 fi
-
+scoring
+cleanTemp
 exit $EXITCODE
