fix(instance-metadata): Credentials recovering

diff --git a/include/assume_role b/include/assume_role
--- a/include/assume_role
+++ b/include/assume_role
@@ -88,10 +88,14 @@ cleanSTSAssumeFile() {
 }
 
 backupInitialAWSCredentials() {
-    if [[ $(printenv AWS_ACCESS_KEY_ID) && $(printenv AWS_SECRET_ACCESS_KEY) && $(printenv AWS_SESSION_TOKEN) ]]; then
+    if [[ $(printenv AWS_ACCESS_KEY_ID) && $(printenv AWS_SECRET_ACCESS_KEY) && $(printenv AWS_SESSION_TOKEN) ]]
+    then
         INITIAL_AWS_ACCESS_KEY_ID=$(printenv AWS_ACCESS_KEY_ID)
         INITIAL_AWS_SECRET_ACCESS_KEY=$(printenv AWS_SECRET_ACCESS_KEY)
         INITIAL_AWS_SESSION_TOKEN=$(printenv AWS_SESSION_TOKEN)
+    else
+        echo -e "$RED ERROR Can't Backup Initial AWS Credentials $NORMAL"
+        exit 1
     fi
 }
 
