refactor(Prowler): Main logic refactor (#1189)
* fix(aws_profile_loader): New functions

* fix(shellcheck): Temporary remove Shellcheck

* fix(aws_cli_detector): new function

* fix(jq_detector): New function

* fix(os_detector): New function

* fix(output_bucket): Output bucket input check in main

* fix(python_detector): deleted unused python detector

* fix(credentials): credentials check out of whoami

* [break]refactor(main)

* [BREAK] Get list of checks parsing all input options

* [break]refactor(main): execute checks functions

* [break]refactor(main): move functions to libs

* fix(validations): custom check validation and typos

* refactor(validate_options): Include comments

* fix(custom_checks): Minor fixes

* refactor(closing_files): include libraries

* refactor(loader): Include ignored checks

* refactor(main): Fix shellcheck

* refactor(loader): beautify

* refactor(monochrome): without variables

* refactor(modes): MODES array not needed

* refactor(whoami): get error from AWSCLI

* refactor(secrets-detector)

* refactor(secrets-detector)

* fix(html_scoring): html scoring was fixed.

* fix(load_checks_from_file)

* fix(color-code): Print if not mono

* fix(not extra): Fixed if EXCLUDE_CHECK_ID is empty

* fix(IFS): Restore default IFS once modes are parsed

* fix(bucket): validate before whoami

* fix(bucket): validate before whoami

Co-authored-by: n4ch04 <nachor1992@gmail.com>
Co-authored-by: sergargar <sergio@verica.io>
Co-authored-by: Nacho Rivera <59198746+n4ch04@users.noreply.github.com>

diff --git a/include/aws_profile_loader b/include/aws_profile_loader
--- a/include/aws_profile_loader
+++ b/include/aws_profile_loader
@@ -16,43 +16,60 @@
 # check environment variables and if not, it checks and loads credentials from
 # instance profile (metadata server) if runs in an EC2 instance
 
-INSTANCE_PROFILE=$(curl -s -m 1 http://169.254.169.254/latest/meta-data/iam/security-credentials/)
-if echo "$INSTANCE_PROFILE" | grep -q '404 - Not Found'; then
-    INSTANCE_PROFILE=
-fi
+aws_profile_loader() {
+    INSTANCE_PROFILE=$(curl -s -m 1 http://169.254.169.254/latest/meta-data/iam/security-credentials/)
+    if echo "$INSTANCE_PROFILE" | grep -q '404 - Not Found'; then
+        INSTANCE_PROFILE=
+    fi
 
-if [[ $PROFILE ]]; then
-  PROFILE_OPT="--profile $PROFILE"
-elif [[ $AWS_ACCESS_KEY_ID && $AWS_SECRET_ACCESS_KEY || $AWS_SESSION_TOKEN || $AWS_PROFILE ]];then
-    PROFILE="$AWS_PROFILE"
-    PROFILE_OPT=""
-elif [[ -n $AWS_CONTAINER_CREDENTIALS_RELATIVE_URI ]] && [[ -z $INSTANCE_PROFILE ]]; then
-    PROFILE="INSTANCE-PROFILE"
-    AWS_ACCESS_KEY_ID=$(curl -s 169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI | grep AccessKeyId | cut -d':' -f2 | sed 's/[^0-9A-Z]*//g')
-    AWS_SECRET_ACCESS_KEY_ID=$(curl -s 169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI | grep SecretAccessKey | cut -d':' -f2 | sed 's/[^0-9A-Za-z/+=]*//g')
-    AWS_SESSION_TOKEN=$(curl -s 169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI  grep Token| cut -d':' -f2 | sed 's/[^0-9A-Za-z/+=]*//g')
-elif [[ $AWS_WEB_IDENTITY_TOKEN_FILE ]]; then
-    PROFILE=""
-    PROFILE_OPT=""
-elif [[ $INSTANCE_PROFILE ]]; then
-    PROFILE="INSTANCE-PROFILE"
-    AWS_ACCESS_KEY_ID=$(curl -s http://169.254.169.254/latest/meta-data/iam/security-credentials/${INSTANCE_PROFILE} | grep AccessKeyId | cut -d':' -f2 | sed 's/[^0-9A-Z]*//g')
-    AWS_SECRET_ACCESS_KEY_ID=$(curl -s http://169.254.169.254/latest/meta-data/iam/security-credentials/${INSTANCE_PROFILE} | grep SecretAccessKey | cut -d':' -f2 | sed 's/[^0-9A-Za-z/+=]*//g')
-    AWS_SESSION_TOKEN=$(curl -s http://169.254.169.254/latest/meta-data/iam/security-credentials/${INSTANCE_PROFILE}  grep Token| cut -d':' -f2 | sed 's/[^0-9A-Za-z/+=]*//g')
-elif [[ $AWS_EXECUTION_ENV == "CloudShell" ]]; then
-    PROFILE_OPT=""
-else
-    PROFILE="default"
+    if [[ $PROFILE ]]; then
     PROFILE_OPT="--profile $PROFILE"
-fi
-# Backing up $PROFILE_OPT needed to renew assume_role
-PROFILE_OPT_BAK=$PROFILE_OPT
-# Set default region by aws config, fall back to us-east-1
-REGION_CONFIG=$(aws configure get region)
-if [[ $REGION_OPT ]]; then
-    REGION="$REGION_OPT"
-elif [[ $REGION_CONFIG ]]; then
-    REGION="$REGION_CONFIG"
-else
-    REGION="us-east-1"
-fi
+    elif [[ $AWS_ACCESS_KEY_ID && $AWS_SECRET_ACCESS_KEY || $AWS_SESSION_TOKEN || $AWS_PROFILE ]];then
+        PROFILE="$AWS_PROFILE"
+        PROFILE_OPT=""
+    elif [[ -n $AWS_CONTAINER_CREDENTIALS_RELATIVE_URI ]] && [[ -z $INSTANCE_PROFILE ]]; then
+        PROFILE="INSTANCE-PROFILE"
+        AWS_ACCESS_KEY_ID=$(curl -s 169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI | grep AccessKeyId | cut -d':' -f2 | sed 's/[^0-9A-Z]*//g')
+        AWS_SECRET_ACCESS_KEY_ID=$(curl -s 169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI | grep SecretAccessKey | cut -d':' -f2 | sed 's/[^0-9A-Za-z/+=]*//g')
+        AWS_SESSION_TOKEN=$(curl -s 169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI  grep Token| cut -d':' -f2 | sed 's/[^0-9A-Za-z/+=]*//g')
+    elif [[ $AWS_WEB_IDENTITY_TOKEN_FILE ]]; then
+        PROFILE=""
+        PROFILE_OPT=""
+    elif [[ $INSTANCE_PROFILE ]]; then
+        PROFILE="INSTANCE-PROFILE"
+        AWS_ACCESS_KEY_ID=$(curl -s http://169.254.169.254/latest/meta-data/iam/security-credentials/${INSTANCE_PROFILE} | grep AccessKeyId | cut -d':' -f2 | sed 's/[^0-9A-Z]*//g')
+        AWS_SECRET_ACCESS_KEY_ID=$(curl -s http://169.254.169.254/latest/meta-data/iam/security-credentials/${INSTANCE_PROFILE} | grep SecretAccessKey | cut -d':' -f2 | sed 's/[^0-9A-Za-z/+=]*//g')
+        AWS_SESSION_TOKEN=$(curl -s http://169.254.169.254/latest/meta-data/iam/security-credentials/${INSTANCE_PROFILE}  grep Token| cut -d':' -f2 | sed 's/[^0-9A-Za-z/+=]*//g')
+    elif [[ $AWS_EXECUTION_ENV == "CloudShell" ]]; then
+        PROFILE_OPT=""
+    else
+        PROFILE="default"
+        PROFILE_OPT="--profile $PROFILE"
+    fi
+    # Backing up $PROFILE_OPT needed to renew assume_role
+    PROFILE_OPT_BAK=$PROFILE_OPT
+    # Set default region by aws config, fall back to us-east-1
+    REGION_CONFIG=$(aws configure get region)
+    if [[ $REGION_OPT ]]; then
+        REGION="$REGION_OPT"
+    elif [[ $REGION_CONFIG ]]; then
+        REGION="$REGION_CONFIG"
+    else
+        REGION="us-east-1"
+    fi
+}
+
+# Function to get all regions
+get_regions() {
+  # Get list of regions based on include/whoami
+  if ! REGIONS=$($AWSCLI ec2 describe-regions \
+            --query 'Regions[].RegionName' \
+            --output text ${PROFILE_OPT} \
+            --region "${REGION_FOR_STS}" \
+            --region-names ${FILTERREGION//[,]/ } 2>&1)
+  then
+    echo "$OPTRED Access Denied trying to describe regions! Review permissions as described here: https://github.com/prowler-cloud/prowler/#requirements-and-installation $OPTNORMAL"
+    EXITCODE=1
+    exit $EXITCODE
+  fi
+}
diff --git a/include/awscli_detector b/include/awscli_detector
--- a/include/awscli_detector
+++ b/include/awscli_detector
@@ -12,12 +12,25 @@
 # specific language governing permissions and limitations under the License.
 
 # AWS-CLI detector variable
-if [ ! -z $(which aws) ]; then
-  AWSCLI=$(which aws)
-elif [ ! -z $(type -p aws) ]; then
-  AWSCLI=$(type -p aws)
-else
-  echo -e "\n$RED ERROR!$NORMAL AWS-CLI (aws command) not found. Make sure it is installed correctly and in your \$PATH\n"
-  EXITCODE=1
-  exit $EXITCODE
-fi
+aws_cli_detector() {
+  if [ ! -z $(which aws) ]; then
+    AWSCLI=$(which aws)
+  elif [ ! -z $(type -p aws) ]; then
+    AWSCLI=$(type -p aws)
+  else
+    echo -e "\n$RED ERROR!$NORMAL AWS-CLI (aws command) not found. Make sure it is installed correctly and in your \$PATH\n"
+    EXITCODE=1
+    exit $EXITCODE
+  fi
+}
+
+set_aws_default_output() {
+  # Ensures command output will always be set to JSON.
+  # If the default value is already set, ORIGINAL_OUTPUT will be used to store it and reset it at cleanup
+  if [[ -z "${AWS_DEFAULT_OUTPUT}" ]]; then
+    ORIGINAL_OUTPUT=$AWS_DEFAULT_OUTPUT
+    export AWS_DEFAULT_OUTPUT="json"
+  else
+    export AWS_DEFAULT_OUTPUT="json"
+  fi
+}
diff --git a/include/custom_checks b/include/custom_checks
--- a/include/custom_checks
+++ b/include/custom_checks
@@ -14,39 +14,39 @@
 custom_checks(){
   # check if the path is an S3 URI
   if grep -q -E "^s3://([^/]+)/?(.*?([^/]+)/?)?$" <<< "$EXTERNAL_CHECKS_PATH"; then
-    if grep -q "check*" <<< "$("${AWSCLI}" s3 ls "${EXTERNAL_CHECKS_PATH}" $PROFILE_OPT)"; then
+    if grep -q "check*" <<< "$("${AWSCLI}" s3 ls "${EXTERNAL_CHECKS_PATH}" "${PROFILE_OPT}")"; then
       # download s3 object
-      echo -e "$NOTICE Downloading custom checks from S3 URI $EXTERNAL_CHECKS_PATH...$NORMAL"
-      S3_CHECKS_TEMP_FOLDER="$PROWLER_DIR/s3-custom-checks"
+      echo -e "${NOTICE} Downloading custom checks from S3 URI ${EXTERNAL_CHECKS_PATH}...${NORMAL}"
+      S3_CHECKS_TEMP_FOLDER="${PROWLER_DIR}/s3-custom-checks"
       mkdir "${S3_CHECKS_TEMP_FOLDER}"
-      $AWSCLI s3 sync "$EXTERNAL_CHECKS_PATH" "${S3_CHECKS_TEMP_FOLDER}" $PROFILE_OPT > /dev/null
+      ${AWSCLI} s3 sync "${EXTERNAL_CHECKS_PATH}" "${S3_CHECKS_TEMP_FOLDER}" "${PROFILE_OPT}" > /dev/null
       # verify if there are checks
-      for checks in "${S3_CHECKS_TEMP_FOLDER}"/check*; do
-        . "$checks"
-        echo -e "$OK Check $(basename "$checks") was included!$NORMAL"
+      for CHECKS in "${S3_CHECKS_TEMP_FOLDER}"/check*; do
+        . "${CHECKS}"
+        echo -e "${OK} Check $(basename "${CHECKS}") was included!${NORMAL}"
       done
-    echo -e "$OK Success! Custom checks were downloaded and included, starting Prowler...$NORMAL"
+    echo -e "${OK} Success! Custom checks were downloaded and included, starting Prowler...${NORMAL}"
     # remove temporary dir
     rm -rf "${S3_CHECKS_TEMP_FOLDER}"
     else
-      echo "$BAD FAIL! Access Denied trying to download custom checks or $EXTERNAL_CHECKS_PATH does not contain any checks, please make sure it is correct and/or you have permissions to get the S3 objects.$NORMAL"
+      echo "${BAD} FAIL! Access Denied trying to download custom checks or ${EXTERNAL_CHECKS_PATH} does not contain any checks, please make sure it is correct and/or you have permissions to get the S3 objects.${NORMAL}"
       EXITCODE=1
       # remove temporary dir
       rm -rf "${S3_CHECKS_TEMP_FOLDER}"
-      exit $EXITCODE
+      exit "${EXITCODE}"
     fi
   else
     # verify if input directory exists with checks
     if ls "${EXTERNAL_CHECKS_PATH}"/check* > /dev/null 2>&1; then
-      for checks in "${EXTERNAL_CHECKS_PATH}"/check*; do
-        . "$checks"
-        echo -e "$OK Check $(basename "$checks") was included!$NORMAL"
+      for CHECKS in "${EXTERNAL_CHECKS_PATH}"/check*; do
+        . "${CHECKS}"
+        echo -e "${OK} Check $(basename "${CHECKS}") was included!${NORMAL}"
       done
-      echo -e "$OK Success! Custom checks were included, starting Prowler...$NORMAL"
+      echo -e "${OK} Success! Custom checks were included, starting Prowler...${NORMAL}"
     else
-      echo "$BAD FAIL! $EXTERNAL_CHECKS_PATH does not exist or not contain checks, please input a valid custom checks path.$NORMAL"
+      echo "${BAD} FAIL! ${EXTERNAL_CHECKS_PATH} does not exist or not contain checks, please input a valid custom checks path.${NORMAL}"
       EXITCODE=1
-      exit $EXITCODE
+      exit "${EXITCODE}"
     fi
   fi
 }
diff --git a/include/tools_detector b/include/tools_detector
--- a/include/tools_detector
+++ b/include/tools_detector
@@ -11,10 +11,20 @@
 # CONDITIONS OF ANY KIND, either express or implied. See the License for the
 # specific language governing permissions and limitations under the License.
 
-# AWS-CLI detector variable
-JQ=$(which jq)
-if [ -z "${JQ}" ]; then
-  echo -e "\n$RED ERROR!$NORMAL jq not found. Make sure it is installed correctly and in your \$PATH\n"
-  EXITCODE=1
-  exit $EXITCODE
-fi
+jq_detector() {
+  if ! command -v jq &>/dev/null
+  then
+    echo -e "\n$RED ERROR!$NORMAL jq not found. Make sure it is installed correctly and in your \$PATH\n"
+    EXITCODE=1
+    exit $EXITCODE
+  fi
+}
+
+curl_detector() {
+  if ! command -v curl &>/dev/null
+  then
+    echo -e "\n$RED ERROR!$NORMAL curl not found. Make sure it is installed correctly and in your \$PATH\n"
+    EXITCODE=1
+    exit $EXITCODE
+  fi
+}
