fix(aws_cli_detector): new function

diff --git a/include/awscli_detector b/include/awscli_detector
--- a/include/awscli_detector
+++ b/include/awscli_detector
@@ -12,12 +12,14 @@
 # specific language governing permissions and limitations under the License.
 
 # AWS-CLI detector variable
-if [ ! -z $(which aws) ]; then
-  AWSCLI=$(which aws)
-elif [ ! -z $(type -p aws) ]; then
-  AWSCLI=$(type -p aws)
-else
-  echo -e "\n$RED ERROR!$NORMAL AWS-CLI (aws command) not found. Make sure it is installed correctly and in your \$PATH\n"
-  EXITCODE=1
-  exit $EXITCODE
-fi
+aws_cli_detector() {
+  if [ ! -z $(which aws) ]; then
+    AWSCLI=$(which aws)
+  elif [ ! -z $(type -p aws) ]; then
+    AWSCLI=$(type -p aws)
+  else
+    echo -e "\n$RED ERROR!$NORMAL AWS-CLI (aws command) not found. Make sure it is installed correctly and in your \$PATH\n"
+    EXITCODE=1
+    exit $EXITCODE
+  fi
+}
