[break]refactor(main): move functions to libs

diff --git a/include/tools_detector b/include/tools_detector
--- a/include/tools_detector
+++ b/include/tools_detector
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-# Prowler - the handy cloud security tool (copyright 2019) by Toni de la Fuente
+# Prowler - the handy cloud security tool (copyright 2018) by Toni de la Fuente
 #
 # Licensed under the Apache License, Version 2.0 (the "License"); you may not
 # use this file except in compliance with the License. You may obtain a copy
@@ -11,10 +11,20 @@
 # CONDITIONS OF ANY KIND, either express or implied. See the License for the
 # specific language governing permissions and limitations under the License.
 
-GROUP_ID[11]='secrets'
-GROUP_NUMBER[11]='11.0'
-GROUP_TITLE[11]='Look for keys secrets or passwords around resources - [secrets]'
-GROUP_CHECKS[11]='extra741,extra742,extra759,extra760,extra768,extra775,extra7141'
+jq_detector() {
+  if ! command -v jq &>/dev/null
+  then
+    echo -e "\n$RED ERROR!$NORMAL jq not found. Make sure it is installed correctly and in your \$PATH\n"
+    EXITCODE=1
+    exit $EXITCODE
+  fi
+}
 
-# requires https://github.com/Yelp/detect-secrets
-# `pip install detect-secrets`
+curl_detector() {
+  if ! command -v curl &>/dev/null
+  then
+    echo -e "\n$RED ERROR!$NORMAL curl not found. Make sure it is installed correctly and in your \$PATH\n"
+    EXITCODE=1
+    exit $EXITCODE
+  fi
+}
diff --git a/include/whoami b/include/whoami
--- a/include/whoami
+++ b/include/whoami
@@ -63,3 +63,32 @@ getWhoami(){
     fi
   fi
 }
+
+get_aws_credentials() {
+  case "$REGION" in
+    me-south-1|eu-south-1|ap-east-1|af-south-1)
+      REGION_FOR_STS="us-east-1"
+    ;;
+    *)
+      REGION_FOR_STS=$REGION
+    ;;
+  esac
+
+  if ! GETCALLER=$("${AWSCLI}" sts get-caller-identity \
+                    ${PROFILE_OPT} \
+                  --output text \
+                  --region "${REGION_FOR_STS}" \
+                  --query '[Arn,UserId,Account]')
+  then
+      echo -e "$RED ERROR Getting credentials to run Prowler - EXITING! $NORMAL"
+      EXITCODE=2
+      exit $EXITCODE
+  fi
+  read -r CALLER_ARN USER_ID ACCOUNT_NUM <<< "${GETCALLER}"
+
+  if [[ $ACCOUNT_TO_ASSUME ]]
+  then
+    ACCOUNT_NUM=$ACCOUNT_TO_ASSUME
+  fi
+  AWS_PARTITION=$(cut -d: -f2 <<< "${CALLER_ARN}")
+}
