refactor(modes): MODES array not needed

diff --git a/include/whoami b/include/whoami
--- a/include/whoami
+++ b/include/whoami
@@ -19,36 +19,11 @@
 # when invoking regions with -r, those regions with STS disabled make GETCALLER fail then
 # this if will filter them out (Africa (Cape Town), Asia Pacific (Hong Kong), Europe (Milan) and Middle East (Bahrain) ):
 
-
-
-
-getWhoami(){
-  echo $MONOCHROME
-    echo ""
-    echo -e " This report is being generated using credentials below:\n"
-    echo -e " AWS-CLI Profile: $NOTICE[$PROFILE]$NORMAL AWS API Region: $NOTICE[$REGION]$NORMAL AWS Filter Region: $NOTICE[${FILTERREGION:-all}]$NORMAL"
-    if [[ $MONOCHROME -eq 1 ]]; then
-      echo -e " AWS Account: $NOTICE[$ACCOUNT_NUM]$NORMAL UserId: $NOTICE[$USER_ID]$NORMAL"
-      echo -e " Caller Identity ARN: $NOTICE[$CALLER_ARN]$NORMAL"
-      if [[ 255 -eq $? ]]; then
-        # Failed to get own identity ... exit
-        echo "ERROR WITH $PROFILE CREDENTIALS - EXITING!"
-        >&2 echo "ERROR WITH $PROFILE CREDENTIALS - EXITING!"
-        exit 2
-      fi
-    else
-      echo -e " AWS Account: $NOTICE[$ACCOUNT_NUM]$NORMAL UserId: $NOTICE[$USER_ID]$NORMAL"
-      echo -e " Caller Identity ARN: $NOTICE[$CALLER_ARN]$NORMAL"
-      if [[ 255 -eq $? ]]; then
-        # Failed to get own identity ... exit
-        echo variable $PROFILE_OPT
-        echo "ERROR WITH $PROFILE CREDENTIALS - EXITING!"
-        >&2 echo "ERROR WITH $PROFILE CREDENTIALS - EXITING!"
-        EXITCODE=2
-        exit $EXITCODE
-      fi
-      echo ""
-    fi
+print_whoami(){
+    echo -e "\n This report is being generated using credentials below:\n"
+    echo -e " AWS-CLI Profile: ${NOTICE}[${PROFILE}]${NORMAL} AWS API Region: ${NOTICE}[${REGION}]${NORMAL} AWS Filter Region: ${NOTICE}[${FILTERREGION:-all}]${NORMAL}"
+    echo -e " AWS Account: ${NOTICE}[${ACCOUNT_NUM}]${NORMAL} UserId: ${NOTICE}[${USER_ID}]${NORMAL}"
+    echo -e " Caller Identity ARN: ${NOTICE}[${CALLER_ARN}]${NORMAL}\n"
 }
 
 get_aws_credentials() {
@@ -67,9 +42,9 @@ get_aws_credentials() {
                   --region "${REGION_FOR_STS}" \
                   --query '[Arn,UserId,Account]')
   then
-      echo -e "$RED ERROR Getting credentials to run Prowler - EXITING! $NORMAL"
-      EXITCODE=2
-      exit $EXITCODE
+    echo -e "$RED ERROR Getting credentials to run Prowler - EXITING! $NORMAL"
+    EXITCODE=2
+    exit $EXITCODE
   fi
   read -r CALLER_ARN USER_ID ACCOUNT_NUM <<< "${GETCALLER}"
 
@@ -77,5 +52,8 @@ get_aws_credentials() {
   then
     ACCOUNT_NUM=$ACCOUNT_TO_ASSUME
   fi
+
+  # Set AWS partition
   AWS_PARTITION=$(cut -d: -f2 <<< "${CALLER_ARN}")
+  export AWS_PARTITION
 }
