Improved GetCallerIdentity handling / credentials

diff --git a/include/whoami b/include/whoami
--- a/include/whoami
+++ b/include/whoami
@@ -13,7 +13,16 @@
 
 
 # Get whoami in AWS, who is the user running this shell script
+
 ACCOUNT_NUM=$($AWSCLI sts get-caller-identity --output text $PROFILE_OPT --region $REGION --query "Account")
+
+if [[ 255 -eq $? ]]; then
+        # Failed to get own identity ... exit
+        echo -e "$RED ERROR Getting credentials to run Prowler - EXITING! $NORMAL"
+        EXITCODE=2
+        exit $EXITCODE
+fi
+
 CALLER_ARN=$($AWSCLI sts get-caller-identity --output text $PROFILE_OPT --region $REGION --query "Arn")
 USER_ID=$($AWSCLI sts get-caller-identity --output text $PROFILE_OPT --region $REGION --query "UserId")
 
